### ISSUE TITLE
Faile on os x with runtime error: could not synchronise with container process: not a directory

### ISSUE THREAD

**Issue by gernest** [influxdata/TICK-docker#6]
Hi, I am trying to run this stack on my machine. And It gives me an error everytime i run the docker compose command.
This is the full output from running `docker-compose up -d `

```bash
013_influxdb_1 is up-to-date
013_kapacitor_1 is up-to-date
Starting 013_influxdb-cli_1
013_chronograf_1 is up-to-date
Starting 013_telegraf_1
Starting 013_kapacitor-cli_1

ERROR: for telegraf  rpc error: code = 2 desc = "oci runtime error: could not synchronise with container process: not a directory"
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
```

I'm running docker
```bash
$ docker  version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

I'm using os x yosemite

**Comment by gernest** [comment]
And snother thing, I forgot to mention is I ran the command in the `0.13` directory

**Comment by gitrago** [comment]
If you run into this, make sure to create the `./etc` folder and put  [telegraf.conf](https://github.com/influxdata/TICK-docker/blob/master/1.3/etc/telegraf.conf) in it. Otherwise docker will create an empty _folder_ named `./etc/telegraf.conf` and will try to bind a _file_ to it.
